version: '2'
services:
  jogueonline-postgresql:
    image: postgres:12.1
    # volumes:
    #     - ~/volumes/jhipster/jogueOnline/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=jogueOnline
      - POSTGRES_PASSWORD=
    ports:
      - 5432:5432
